# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-14 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anvilgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='cnn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='网址')),
                ('url_object_id', models.CharField(max_length=255, verbose_name='网址id')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('create_date', models.CharField(max_length=255, verbose_name='时间')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签')),
                ('content', models.TextField(verbose_name='信息')),
                ('content_text', models.TextField(verbose_name='文本信息')),
            ],
            options={
                'verbose_name': '文章信息',
                'verbose_name_plural': '文章信息详情',
            },
        ),
        migrations.CreateModel(
            name='grada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='网址')),
                ('url_object_id', models.CharField(max_length=255, verbose_name='网址id')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('abstract', models.TextField(verbose_name='摘要')),
                ('create_date', models.CharField(max_length=255, verbose_name='时间')),
                ('country', models.CharField(max_length=255, verbose_name='地区')),
                ('happen_time', models.CharField(max_length=255, verbose_name='事件的开始时间')),
                ('warning_interval_time', models.CharField(max_length=255, verbose_name='事件的预警时间')),
                ('content', models.TextField(verbose_name='信息')),
                ('event', models.TextField(blank=True, null=True, verbose_name='事件')),
                ('analyze', models.TextField(verbose_name='对事件的分析')),
                ('advice', models.TextField(verbose_name='对事件的建议')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签')),
                ('relevant_early_warning', models.TextField(verbose_name='事件的最近相关的预警')),
            ],
            options={
                'verbose_name': '文章信息',
                'verbose_name_plural': '文章信息详情',
            },
        ),
        migrations.CreateModel(
            name='mondaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='网址')),
                ('url_object_id', models.CharField(max_length=255, verbose_name='网址id')),
                ('title', models.CharField(max_length=255, verbose_name='文章标题')),
                ('create_date', models.CharField(max_length=255, verbose_name='文章创建时间')),
                ('country', models.CharField(max_length=255, verbose_name='地区')),
                ('authors', models.CharField(max_length=255, verbose_name='文章作者')),
                ('organization', models.CharField(max_length=255, verbose_name='文章所属机构或组织')),
                ('tags', models.CharField(max_length=255, verbose_name='标签')),
                ('content', models.TextField(verbose_name='文章内容')),
            ],
            options={
                'verbose_name': '文章信息',
                'verbose_name_plural': '文章信息详情',
            },
        ),
        migrations.CreateModel(
            name='osac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='网址')),
                ('url_object_id', models.CharField(max_length=255, verbose_name='网址id')),
                ('article_type', models.IntegerField(verbose_name='文章类别')),
                ('create_date', models.CharField(max_length=255, verbose_name='时间')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='信息')),
                ('content_text', models.TextField(verbose_name='文本信息')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='地区')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='城市')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='地点')),
                ('event', models.TextField(blank=True, null=True, verbose_name='事件')),
                ('action', models.TextField(blank=True, null=True, verbose_name='活动')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签')),
                ('travel_level', models.IntegerField(blank=True, null=True, verbose_name='级别')),
            ],
            options={
                'verbose_name': '文章信息',
                'verbose_name_plural': '文章信息详情',
            },
        ),
    ]
