# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-14 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anvilgroup',
            options={'verbose_name': '文章信息', 'verbose_name_plural': '文章信息详情'},
        ),
        migrations.AddField(
            model_name='anvilgroup',
            name='content',
            field=models.TextField(default='', verbose_name='信息'),
        ),
        migrations.AddField(
            model_name='anvilgroup',
            name='content_text',
            field=models.TextField(default='', verbose_name='文本信息'),
        ),
        migrations.AddField(
            model_name='anvilgroup',
            name='country',
            field=models.CharField(default='', max_length=255, verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='anvilgroup',
            name='crawl_date',
            field=models.CharField(default='', max_length=255, verbose_name='爬取时间'),
        ),
        migrations.AddField(
            model_name='anvilgroup',
            name='create_date',
            field=models.CharField(default='', max_length=255, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='anvilgroup',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='事件的等级'),
        ),
        migrations.AddField(
            model_name='anvilgroup',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='anvilgroup',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='网址'),
        ),
        migrations.AddField(
            model_name='anvilgroup',
            name='url_object_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='网址id'),
        ),
    ]
